package com.susu.java;

/**
 * @author fxbsujay@gmail.com
 * <p> Description: Find the Difference</p>
 * @version 0:50 2022/4/7
 * @since JDK1.8
 */
public class FindTheDifference {

    /**
     * <p> 给定两个字符串 s 和 t ，它们只包含小写字母 </p>
     * <p> 字符串 t 由字符串 s 随机重排，然后在随机位置添加一个字母 </p>
     * <p> 请找出在 t 中被添加的字母 </p>
     *
     * <p> You are given two strings s and t </p>
     * <p> String t is generated by random shuffling string s and then add one more letter at a random position </p>
     * <p> Return the letter that was added to t </p>
     *
     * <blockquote><pre>
     * Example :
     *
     * Input   : s = "abcd", t = "abcde"
     *
     * Output  : "e"
     *
     * Explanation: 'e' is the letter that was added
     * </pre></blockquote>
     *
     * @param s 原字符串
     * @param t 目标字符串
     * @return 在 t 中被添加的字母
     */
    public static char findTheDifference(String s, String t) {
        int result = 0;
        for (int i = 0; i < s.length(); i++) {
            result ^= s.charAt(i);
        }
        for (int i = 0; i < t.length(); i++) {
            result ^= t.charAt(i);
        }
        return (char) result;
    }

    public static void main(String[] args) {
        char result = findTheDifference("abcd", "abcde");
        System.out.println(result);
    }
}
