""""
# version:python 3.10
# -*- coding:utf-8 -*-

--------------------
# @Author       : fxbsujay@gmail.com
# @Time         : 12:37 2022/4/8 
# @File         : FindTheDifference.py
# @Version      : Python 3.10
# @Description  : 找不同
--------------------
"""

"""
给定两个字符串 s 和 t ，它们只包含小写字母
字符串 t 由字符串 s 随机重排，然后在随机位置添加一个字母
请找出在 t 中被添加的字母

You are given two strings s and t
String t is generated by random shuffling string s and then add one more letter at a random position
Return the letter that was added to t

--------------------
Example : 
Input   :  s = "abcd", t = "abcde"
Output  :  "e"
--------------------   
"""


def findTheDifference(s: str, t: str) -> str:
    res = 0
    for i in s:
        res ^= ord(i)
    for i in t:
        res ^= ord(i)
    return chr(res)


if __name__ == '__main__':
    result = findTheDifference("abcd", "abcde")
    print(result)
